language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: ILLUMINATE_VERSION=5.2.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.3.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.*

before_script:
  - composer self-update
  - composer config secure-http false
  - composer config disable-tls true
  - composer config
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
  - composer update -vvv
